# Generated by Django 3.2.24 on 2024-05-23 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('prayer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('point', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('points', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='static/user')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prayapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Prayer_marking',
            fields=[
                ('prayer_mark_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=200)),
                ('ontime', models.CharField(max_length=200)),
                ('aftertime', models.CharField(max_length=200)),
                ('with_imam', models.CharField(max_length=200)),
                ('missed', models.CharField(max_length=200)),
                ('prayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prayapp.prayer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prayapp.user')),
            ],
        ),
    ]
